# Generated by Django 6.0.5 on 2026-05-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
